name: Node.js CI  # GitHub Workflow Name

on:
  push:
    branches: 
      - master     # Runs when pushing to master branch
  pull_request:     # Optional: runs also when PR is created
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub provides this VM

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones your repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'   # Make sure it matches your local Node.js version

      - name: Install Dependencies
        run: npm install   # Installs from package.json

      - name: Run Linter
        run: npm run lint  # Optional: runs your linter (if set)

      - name: Run Tests
        run: npm test      # Executes your unit tests

      - name: Build Project
        run: npm run build # Builds your React project for production
